DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS charities CASCADE;
DROP TABLE IF EXISTS employees CASCADE;
DROP TABLE IF EXISTS donations CASCADE;

CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  firstName VARCHAR(255) NOT NULL,
  lastName VARCHAR(255) NOT NULL,
  address VARCHAR(255) NOT NULL,
  city VARCHAR(255) NOT NULL,
  province VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE charities (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  address VARCHAR(255) NOT NULL,
  city VARCHAR(255) NOT NULL,
  province VARCHAR(255) NOT NULL,
  shortDescription VARCHAR(255) NOT NULL,
  longDescription TEXT,
  qrImgUrl VARCHAR(255),
  logo VARCHAR(255) NOT NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE employees (
  id SERIAL PRIMARY KEY NOT NULL,
  firstName VARCHAR(255) NOT NULL,
  lastName VARCHAR(255) NOT NULL,
  charityId INTEGER REFERENCES charities(id)
);

CREATE TABLE donations (
  id SERIAL PRIMARY KEY NOT NULL,
  amountCents INTEGER NOT NULL,
  userId INTEGER REFERENCES users(id),
  charityId INTEGER REFERENCES charities(id),
  employeeId INTEGER REFERENCES employees(id),
  donatedAt TIMESTAMP NOT NULL DEFAULT NOW()
);